### ISSUE TITLE
LICENSE to be updated for old REC documents?

### ISSUE THREAD

**Issue by ashimura** [w3c/speech-synthesis11#3]
Which W3C license to be applied to old REC documents which use the [W3C Document License](http://www.w3.org/Consortium/Legal/copyright-documents)? Simply keep using the [W3C Document License](http://www.w3.org/Consortium/Legal/copyright-documents) or should use the [W3C Software and Document License](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document) instead?

**Comment by plehegar** [comment]
Same one as used on the original Recommendation.

**Comment by ashimura** [comment]
OK. Thanks!
